name: Bruno Test & Report

on:
  workflow_dispatch:

jobs:
  bruno-tests:
    name: Bruno test collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # <1>
        id: checkout
        uses: actions/checkout@v4

      - name: Bruno CLI runner  # <2>
        id: bru-cli
        uses: krummbar/bruno-run-action@main
        with:
          path: bruno/api-it
          output: bru-output.json # <3>
          outputFormat: json

      - name: Attach bru run summary # <4>
        uses: krummbar/bruno-run-report@main
        continue-on-error: true # <5>
        with:
          run-report-path: bru-output.json # <6>
