= Development
:url-asciidoctor: https://docs.asciidoctor.org/asciidoc/latest/
:url-asciidoctor-reducer: https://github.com/asciidoctor/asciidoctor-reducer
:url-jq: https://jqlang.github.io/jq/

== Test Locally

In order to execute the actual script the action's input parameters must be set as environment variables,
and `jq` needs to be available on the work station.

Prerequisites::
* {url-jq}[jq]

The required input parameters are listed in xref:docs/examples/.env.sample[].

[source,sh]
----
include::examples/.env.sample[]
----

If the environment variables are set according to your needs, the main script can simply be executed.

[source,console]
----
./entrypoint.sh
----

[IMPORTANT]
====
If the above listed values are used, ensure the `out` folder exists and the project's root folder.
Otherwise the script execution may fail.
====

The markdown result is dumped to the configured path in `GITHUB_STEP_SUMMARY`, and if set copied to `IN_OUTPUT_PATH`

=== Explanation

The script uses `jq` to read the JSON report of a bru run process and markdown templates for generic information as the optional footer.
The transform functions and templates are defined in the xref:src[] folder.


== Documentation

The `README.adoc` file is generated from the sources in the link:docs[docs] folder.
Any documentation changes must be applied to the files located in there.

Prerequisites::
* {url-asciidoctor}[AsciiDoc]
* {url-asciidoctor-reducer}[AsciiDoctor Reducer]

In order to update the contents of the `README.adoc` run the following command.

.Update README.adoc
[source,console]
----
asciidoctor-reducer --preserve-conditionals -o README.adoc docs/index.adoc
----

